version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mssql:
    image: mcr.microsoft.com/mssql/server:latest

  cache:
    image: redis:alpine

  matching.api:
    image: ${DOCKER_REGISTRY-}matchingapi
    build:
      context: .
      dockerfile: src/Services/Matching/Matching.Api/Dockerfile

  ocelot.gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: src/ApiGateways/Ocelot.Gateway/Dockerfile


  identity.server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.Server/Dockerfile

